services:
    postgres:
        container_name: postgres
        image: postgres:18.1-alpine3.22
        environment:
            - POSTGRES_DB=default
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=password
            - LANG=pt_BR.utf8
        ports:
            - "5432:5432"

    valkey:
        container_name: valkey
        image: valkey/valkey-bundle:9.0.0-alpine
        entrypoint:
            - valkey-server
            - --loadmodule
            - /usr/lib/valkey/libjson.so
        ports:
            - "6379:6379"

    cap:
        container_name: cap
        image: tiago2/cap:2.0.18
        environment:
            - SERVER_PORT=7930
            - ADMIN_KEY=V3c3Lh/q;,,jg5;@M^u}gsIzNST*iM
        ports:
            - "7930:7930"
