packages:
  - apps/**
  - packages/**

catalog:
  '@types/node': 24.10.1
  dprint: 0.50.2
  pm2: 6.0.14
  tsdown: 0.17.1
  tsx: 4.21.0
  turbo: 2.6.1
  typescript: 5.9.3

catalogs:
  core:
    uuid: 13.0.0
    zod: 4.1.12
  fastify:
    '@fastify/cookie': 11.0.2
    '@fastify/cors': 11.1.0
    '@fastify/rate-limit': 10.3.0
    '@fastify/sensible': 6.0.3
    '@fastify/swagger': 9.6.1
    '@scalar/fastify-api-reference': 1.40.1
    fastify: 5.6.2
    fastify-plugin: 5.1.0
  openapi:
    openapi-fetch: 0.15.0
    openapi-typescript: 7.10.1
    swr-openapi: 5.5.0
  postgres:
    '@types/pg': 8.15.6
    node-pg-migrate: 8.0.3
    pg: 8.16.3
  react:
    '@types/react': 19.2.7
    '@types/react-dom': 19.2.3
    babel-plugin-react-compiler: 1.0.0
    next: 16.0.7
    react: 19.2.1
    react-dom: 19.2.1
  schema:
    '@standard-schema/spec': 1.0.0
    '@standard-schema/utils': 0.3.0
  security:
    '@dotenvx/dotenvx': 1.51.1
    '@types/bcrypt': 6.0.0
    bcrypt: 6.0.0
    paseto-ts: 2.0.5
  sqlite:
    libsql: 0.5.22
  tailwind:
    '@tailwindcss/postcss': 4.1.17
    daisyui: 5.5.5
    tailwindcss: 4.1.17
  valkey:
    iovalkey: 0.3.3

onlyBuiltDependencies:
  - bcrypt
  - esbuild
  - sharp
