/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely'

export type Difficulty = 'easy' | 'hard' | 'medium'

export type Generated<T> =
    T extends ColumnType<infer S, infer I, infer U>
        ? ColumnType<S, I | undefined, U>
        : ColumnType<T, T | undefined, T>

export interface Ingredients {
    id: string
    measure: string
    name: string
    pk: Generated<number>
    recipeId: string
    unit: string
}

export interface Recipes {
    authorId: string
    description: string
    difficulty: Difficulty
    id: string
    name: string
    pk: Generated<number>
    preparationTime: number
}

export interface Steps {
    description: string
    id: string
    order: number
    pk: Generated<number>
    recipeId: string
}

export interface Tools {
    amount: number
    id: string
    name: string
    pk: Generated<number>
    recipeId: string
}

export interface Users {
    email: string
    id: string
    name: string
    password: string
    pk: Generated<number>
}

export interface DB {
    ingredients: Ingredients
    recipes: Recipes
    steps: Steps
    tools: Tools
    users: Users
}
