/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    '/auth/register': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        get?: never
        put?: never
        /** @description Rota para registrar um usuário */
        post: {
            parameters: {
                query?: never
                header?: never
                path?: never
                cookie?: never
            }
            requestBody: {
                content: {
                    'application/json': {
                        /**
                         * Nome de Usuário
                         * @example John Doe
                         */
                        name: string
                        /**
                         * Endereço de Email
                         * Format: email
                         * @example user@example.com
                         */
                        email: string
                        /**
                         * Senha
                         * @example abc123ABC
                         */
                        password: string & string
                    }
                }
            }
            responses: {
                /** @description Usuário cadastrado com sucesso */
                201: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': unknown
                    }
                }
                /** @description Um erro de validação */
                400: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': {
                            error: string
                            message: string
                            /** @enum {number} */
                            statusCode: 400
                        }
                    }
                }
                /** @description O email do usuário já está cadastrado */
                409: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': {
                            error: string
                            message: string
                            statusCode: number
                        }
                    }
                }
                /** @description Um erro inesperado interno do servidor */
                500: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': {
                            error: string
                            message: string
                            /** @enum {number} */
                            statusCode: 500
                        }
                    }
                }
            }
        }
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/auth/login': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        get?: never
        put?: never
        /** @description Rota de login de conta */
        post: {
            parameters: {
                query?: never
                header?: never
                path?: never
                cookie?: never
            }
            requestBody: {
                content: {
                    'application/json': {
                        /**
                         * Endereço de Email
                         * Format: email
                         * @example user@example.com
                         */
                        email: string
                        /**
                         * Senha
                         * @example abc123ABC
                         */
                        password: string & string
                    }
                }
            }
            responses: {
                /** @description Logado com sucesso e retorna token de acesso */
                200: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': {
                            token: string
                        }
                    }
                }
                /** @description Um erro de validação */
                400: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': {
                            error: string
                            message: string
                            /** @enum {number} */
                            statusCode: 400
                        }
                    }
                }
                /** @description Credenciais de acesso incorretas */
                403: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': {
                            error: string
                            message: string
                            statusCode: number
                        }
                    }
                }
                /** @description Não existe um usuário com o email cadastrado */
                404: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': {
                            error: string
                            message: string
                            statusCode: number
                        }
                    }
                }
                /** @description Um erro inesperado interno do servidor */
                500: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': {
                            error: string
                            message: string
                            /** @enum {number} */
                            statusCode: 500
                        }
                    }
                }
            }
        }
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/auth/logout': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /** @description Desconectar o usuário da sessão */
        get: {
            parameters: {
                query?: never
                header?: never
                path?: never
                cookie?: {
                    accessToken?: string
                }
            }
            requestBody?: {
                content: {
                    'application/json': unknown
                }
            }
            responses: {
                /** @description Usuário deconectado com sucesso */
                204: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': unknown
                    }
                }
                /** @description Um erro de validação */
                400: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': {
                            error: string
                            message: string
                            /** @enum {number} */
                            statusCode: 400
                        }
                    }
                }
                /** @description Um erro inesperado interno do servidor */
                500: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': {
                            error: string
                            message: string
                            /** @enum {number} */
                            statusCode: 500
                        }
                    }
                }
            }
        }
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/auth/verify': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /** @description Verificar a sessão do usuário */
        get: {
            parameters: {
                query?: never
                header?: never
                path?: never
                cookie?: {
                    accessToken?: Record<string, never>
                }
            }
            requestBody?: {
                content: {
                    'application/json': unknown
                }
            }
            responses: {
                /** @description A sessão do usuário é válida */
                204: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': unknown
                    }
                }
                /** @description A sessão do usuário é inválida */
                401: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': {
                            error: string
                            message: string
                            statusCode: number
                        }
                    }
                }
                /** @description Um erro inesperado interno do servidor */
                500: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': {
                            error: string
                            message: string
                            /** @enum {number} */
                            statusCode: 500
                        }
                    }
                }
            }
        }
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/cooking/recipes': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /** @description Buscar todas as receitas */
        get: {
            parameters: {
                query?: {
                    search?: string
                    limit?: number
                    offset?: number
                }
                header?: never
                path?: never
                cookie?: {
                    accessToken?: string
                }
            }
            requestBody?: {
                content: {
                    'application/json': unknown
                }
            }
            responses: {
                /** @description Lista de Receitas */
                200: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': {
                            /**
                             * Format: uuid
                             * @default 019c1a1b-8388-742e-a9c1-0063ec517253
                             * @example 019c1a1b-63f6-779f-b83a-7cfcd4d9bd7f
                             */
                            id: string
                            /**
                             * Format: uuid
                             * @default 019c1a1b-8388-742e-a9c1-0063ec517253
                             * @example 019c1a1b-63f6-779f-b83a-7cfcd4d9bd7f
                             */
                            authorId: string
                            name: string
                            description: string
                            /** @enum {string} */
                            difficulty: 'easy' | 'medium' | 'hard'
                            preparationTime: unknown
                            steps: {
                                /**
                                 * Format: uuid
                                 * @default 019c1a1b-8388-742e-a9c1-0063ec517253
                                 * @example 019c1a1b-63f6-779f-b83a-7cfcd4d9bd7f
                                 */
                                id: string
                                order: number
                                description: string
                            }[]
                            tools: {
                                /**
                                 * Format: uuid
                                 * @default 019c1a1b-8388-742e-a9c1-0063ec517253
                                 * @example 019c1a1b-63f6-779f-b83a-7cfcd4d9bd7f
                                 */
                                id: string
                                name: string
                                amount: number
                            }[]
                            ingredients: {
                                /**
                                 * Format: uuid
                                 * @default 019c1a1b-8388-742e-a9c1-0063ec517253
                                 * @example 019c1a1b-63f6-779f-b83a-7cfcd4d9bd7f
                                 */
                                id: string
                                name: string
                                /** @enum {string} */
                                unit:
                                    | 'drop'
                                    | 'pinch'
                                    | 'tsp'
                                    | 'tbsp'
                                    | 'dsp'
                                    | 'ssp'
                                    | 'g'
                                    | 'mg'
                                    | 'kg'
                                    | 'l'
                                    | 'ml'
                                    | 'cup'
                                measure: unknown
                            }[]
                        }[]
                    }
                }
                /** @description Um erro de validação */
                400: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': {
                            error: string
                            message: string
                            /** @enum {number} */
                            statusCode: 400
                        }
                    }
                }
                /** @description Um erro inesperado interno do servidor */
                500: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': {
                            error: string
                            message: string
                            /** @enum {number} */
                            statusCode: 500
                        }
                    }
                }
            }
        }
        put?: never
        /** @description Cadastrar uma receita */
        post: {
            parameters: {
                query?: never
                header?: never
                path?: never
                cookie?: {
                    accessToken?: string
                }
            }
            requestBody: {
                content: {
                    'application/json': {
                        name: string
                        description: string
                        /** @enum {string} */
                        difficulty: 'easy' | 'medium' | 'hard'
                        preparationTime: unknown
                        steps: {
                            /**
                             * Format: uuid
                             * @default 019c1a1b-8383-710e-8d0d-cdf010a6a722
                             * @example 019c1a1b-63f6-779f-b83a-7cfcd4d9bd7f
                             */
                            id?: string
                            order: number
                            description: string
                        }[]
                        tools: {
                            /**
                             * Format: uuid
                             * @default 019c1a1b-8383-710e-8d0d-cdf010a6a722
                             * @example 019c1a1b-63f6-779f-b83a-7cfcd4d9bd7f
                             */
                            id?: string
                            name: string
                            amount: number
                        }[]
                        ingredients: {
                            /**
                             * Format: uuid
                             * @default 019c1a1b-8383-710e-8d0d-cdf010a6a722
                             * @example 019c1a1b-63f6-779f-b83a-7cfcd4d9bd7f
                             */
                            id?: string
                            name: string
                            /** @enum {string} */
                            unit:
                                | 'drop'
                                | 'pinch'
                                | 'tsp'
                                | 'tbsp'
                                | 'dsp'
                                | 'ssp'
                                | 'g'
                                | 'mg'
                                | 'kg'
                                | 'l'
                                | 'ml'
                                | 'cup'
                            measure: unknown
                        }[]
                    }
                }
            }
            responses: {
                /** @description Receita criada com sucesso */
                201: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': unknown
                    }
                }
                /** @description Um erro de validação */
                400: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': {
                            error: string
                            message: string
                            /** @enum {number} */
                            statusCode: 400
                        }
                    }
                }
                /** @description Um erro inesperado interno do servidor */
                500: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': {
                            error: string
                            message: string
                            /** @enum {number} */
                            statusCode: 500
                        }
                    }
                }
            }
        }
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/cooking/recipes/{id}': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /** @description Procurar uma receita */
        get: {
            parameters: {
                query?: never
                header?: never
                path: {
                    /** @example 019c1a1b-63f6-779f-b83a-7cfcd4d9bd7f */
                    id: string
                }
                cookie?: {
                    accessToken?: string
                }
            }
            requestBody?: {
                content: {
                    'application/json': unknown
                }
            }
            responses: {
                /** @description Receita */
                200: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': {
                            /**
                             * Format: uuid
                             * @default 019c1a1b-8387-73c9-a1c9-ffc113be8f1c
                             * @example 019c1a1b-63f6-779f-b83a-7cfcd4d9bd7f
                             */
                            id: string
                            /**
                             * Format: uuid
                             * @default 019c1a1b-8387-73c9-a1c9-ffc113be8f1c
                             * @example 019c1a1b-63f6-779f-b83a-7cfcd4d9bd7f
                             */
                            authorId: string
                            name: string
                            description: string
                            /** @enum {string} */
                            difficulty: 'easy' | 'medium' | 'hard'
                            preparationTime: unknown
                            steps: {
                                /**
                                 * Format: uuid
                                 * @default 019c1a1b-8387-73c9-a1c9-ffc113be8f1c
                                 * @example 019c1a1b-63f6-779f-b83a-7cfcd4d9bd7f
                                 */
                                id: string
                                order: number
                                description: string
                            }[]
                            tools: {
                                /**
                                 * Format: uuid
                                 * @default 019c1a1b-8387-73c9-a1c9-ffc113be8f1c
                                 * @example 019c1a1b-63f6-779f-b83a-7cfcd4d9bd7f
                                 */
                                id: string
                                name: string
                                amount: number
                            }[]
                            ingredients: {
                                /**
                                 * Format: uuid
                                 * @default 019c1a1b-8387-73c9-a1c9-ffc113be8f1c
                                 * @example 019c1a1b-63f6-779f-b83a-7cfcd4d9bd7f
                                 */
                                id: string
                                name: string
                                /** @enum {string} */
                                unit:
                                    | 'drop'
                                    | 'pinch'
                                    | 'tsp'
                                    | 'tbsp'
                                    | 'dsp'
                                    | 'ssp'
                                    | 'g'
                                    | 'mg'
                                    | 'kg'
                                    | 'l'
                                    | 'ml'
                                    | 'cup'
                                measure: unknown
                            }[]
                        }
                    }
                }
                /** @description Um erro de validação */
                400: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': {
                            error: string
                            message: string
                            /** @enum {number} */
                            statusCode: 400
                        }
                    }
                }
                /** @description Um erro inesperado interno do servidor */
                500: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': {
                            error: string
                            message: string
                            /** @enum {number} */
                            statusCode: 500
                        }
                    }
                }
            }
        }
        /** @description Atualizar uma receita cadastrada */
        put: {
            parameters: {
                query?: never
                header?: never
                path: {
                    /** @example 019c1a1b-63f6-779f-b83a-7cfcd4d9bd7f */
                    id: string
                }
                cookie?: {
                    accessToken?: string
                }
            }
            requestBody: {
                content: {
                    'application/json': {
                        /**
                         * Format: uuid
                         * @default 019c1a1b-8385-72d5-b833-1a9f4289e618
                         * @example 019c1a1b-63f6-779f-b83a-7cfcd4d9bd7f
                         */
                        authorId: string
                        name: string
                        description: string
                        /** @enum {string} */
                        difficulty: 'easy' | 'medium' | 'hard'
                        preparationTime: unknown
                        steps: {
                            /**
                             * Format: uuid
                             * @default 019c1a1b-8385-72d5-b833-1a9f4289e618
                             * @example 019c1a1b-63f6-779f-b83a-7cfcd4d9bd7f
                             */
                            id?: string
                            order: number
                            description: string
                        }[]
                        tools: {
                            /**
                             * Format: uuid
                             * @default 019c1a1b-8385-72d5-b833-1a9f4289e618
                             * @example 019c1a1b-63f6-779f-b83a-7cfcd4d9bd7f
                             */
                            id?: string
                            name: string
                            amount: number
                        }[]
                        ingredients: {
                            /**
                             * Format: uuid
                             * @default 019c1a1b-8385-72d5-b833-1a9f4289e618
                             * @example 019c1a1b-63f6-779f-b83a-7cfcd4d9bd7f
                             */
                            id?: string
                            name: string
                            /** @enum {string} */
                            unit:
                                | 'drop'
                                | 'pinch'
                                | 'tsp'
                                | 'tbsp'
                                | 'dsp'
                                | 'ssp'
                                | 'g'
                                | 'mg'
                                | 'kg'
                                | 'l'
                                | 'ml'
                                | 'cup'
                            measure: unknown
                        }[]
                    }
                }
            }
            responses: {
                /** @description Receita atualizada com sucesso */
                204: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': unknown
                    }
                }
                /** @description Um erro de validação */
                400: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': {
                            error: string
                            message: string
                            /** @enum {number} */
                            statusCode: 400
                        }
                    }
                }
                /** @description Um erro inesperado interno do servidor */
                500: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': {
                            error: string
                            message: string
                            /** @enum {number} */
                            statusCode: 500
                        }
                    }
                }
            }
        }
        post?: never
        /** @description Deletar uma receita cadastrada */
        delete: {
            parameters: {
                query?: never
                header?: never
                path: {
                    /** @example 019c1a1b-63f6-779f-b83a-7cfcd4d9bd7f */
                    id: string
                }
                cookie?: {
                    accessToken?: string
                }
            }
            requestBody?: {
                content: {
                    'application/json': unknown
                }
            }
            responses: {
                /** @description Receita deletada com sucesso */
                204: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': unknown
                    }
                }
                /** @description Um erro de validação */
                400: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': {
                            error: string
                            message: string
                            /** @enum {number} */
                            statusCode: 400
                        }
                    }
                }
                /** @description Um erro inesperado interno do servidor */
                500: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': {
                            error: string
                            message: string
                            /** @enum {number} */
                            statusCode: 500
                        }
                    }
                }
            }
        }
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/cooking/authors/{id}/recipes': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /** @description Buscar todas as receitas de um usuário */
        get: {
            parameters: {
                query?: never
                header?: never
                path: {
                    /** @example 019c1a1b-63f6-779f-b83a-7cfcd4d9bd7f */
                    id: string
                }
                cookie?: {
                    accessToken?: string
                }
            }
            requestBody?: {
                content: {
                    'application/json': unknown
                }
            }
            responses: {
                /** @description Lista de Receitas */
                200: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': {
                            /**
                             * Format: uuid
                             * @default 019c1a1b-8389-714f-8c28-a78044dd4dd7
                             * @example 019c1a1b-63f6-779f-b83a-7cfcd4d9bd7f
                             */
                            id: string
                            /**
                             * Format: uuid
                             * @default 019c1a1b-8389-714f-8c28-a78044dd4dd7
                             * @example 019c1a1b-63f6-779f-b83a-7cfcd4d9bd7f
                             */
                            authorId: string
                            name: string
                            description: string
                            /** @enum {string} */
                            difficulty: 'easy' | 'medium' | 'hard'
                            preparationTime: unknown
                            steps: {
                                /**
                                 * Format: uuid
                                 * @default 019c1a1b-8389-714f-8c28-a78044dd4dd7
                                 * @example 019c1a1b-63f6-779f-b83a-7cfcd4d9bd7f
                                 */
                                id: string
                                order: number
                                description: string
                            }[]
                            tools: {
                                /**
                                 * Format: uuid
                                 * @default 019c1a1b-8389-714f-8c28-a78044dd4dd7
                                 * @example 019c1a1b-63f6-779f-b83a-7cfcd4d9bd7f
                                 */
                                id: string
                                name: string
                                amount: number
                            }[]
                            ingredients: {
                                /**
                                 * Format: uuid
                                 * @default 019c1a1b-8389-714f-8c28-a78044dd4dd7
                                 * @example 019c1a1b-63f6-779f-b83a-7cfcd4d9bd7f
                                 */
                                id: string
                                name: string
                                /** @enum {string} */
                                unit:
                                    | 'drop'
                                    | 'pinch'
                                    | 'tsp'
                                    | 'tbsp'
                                    | 'dsp'
                                    | 'ssp'
                                    | 'g'
                                    | 'mg'
                                    | 'kg'
                                    | 'l'
                                    | 'ml'
                                    | 'cup'
                                measure: unknown
                            }[]
                        }[]
                    }
                }
                /** @description Um erro de validação */
                400: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': {
                            error: string
                            message: string
                            /** @enum {number} */
                            statusCode: 400
                        }
                    }
                }
                /** @description Um erro inesperado interno do servidor */
                500: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': {
                            error: string
                            message: string
                            /** @enum {number} */
                            statusCode: 500
                        }
                    }
                }
            }
        }
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
}
export type webhooks = Record<string, never>
export interface components {
    schemas: never
    responses: never
    parameters: never
    requestBodies: never
    headers: never
    pathItems: never
}
export type $defs = Record<string, never>
export type operations = Record<string, never>
